const ETHNICITIES = [
  'arab',
  'african',
  'turkish',
  'caucasian',
  'asian',
  'indian',
  'latin',
];

const REGISTRATION_QUESTIONNAIRE = {
  version: '2026-03-17',
  sections: [
    {
      id: 'common',
      title: 'Informations communes',
      appliesTo: ['male', 'female'],
      fields: [
        { key: 'role', type: 'single_choice', options: ['male', 'female'] },
        { key: 'firstName', type: 'text' },
        { key: 'dateOfBirth', type: 'date' },
        { key: 'nationality', type: 'text_or_select' },
        { key: 'origin', type: 'text_or_select' },
        { key: 'ethnicity', type: 'single_choice', options: ETHNICITIES },
        { key: 'country', type: 'text_or_select' },
        { key: 'city', type: 'text_or_select' },
        { key: 'maritalStatus', type: 'single_choice', options: ['single', 'divorced', 'widowed'] },
        { key: 'hadPreviousMarriage', type: 'single_choice', options: [true, false] },
        { key: 'children.has', type: 'single_choice', options: [true, false] },
        { key: 'children.count', type: 'number_if_children' },
        { key: 'religiousPractice', type: 'single_choice', options: ['little', 'practicing', 'very_practicing'] },
        { key: 'prayers', type: 'single_choice', options: ['regular', 'irregular', 'rarely'] },
        { key: 'religiousFollowing', type: 'single_choice', options: ['none', 'self_taught', 'student'] },
        { key: 'madhhab', type: 'single_choice', options: ['hanafi', 'maliki', 'shafii', 'hanbali', 'none'] },
        { key: 'wantsChildren', type: 'single_choice', options: ['yes', 'no', 'undecided'] },
        { key: 'willingToRelocate', type: 'single_choice', options: [true, false] },
        {
          key: 'hijra',
          type: 'single_choice',
          options: ['already_done', 'possible_with_country', 'not_desired'],
        },
        { key: 'hijraCountry', type: 'text_if_hijra_possible' },
      ],
    },
    {
      id: 'female_profile',
      title: 'Profil specifique soeur',
      appliesTo: ['female'],
      fields: [
        { key: 'physicalCharacteristics.height', type: 'number_cm' },
        { key: 'physicalCharacteristics.bodyType', type: 'single_choice', options: ['slim', 'average', 'strong'] },
        { key: 'femaleProfile.veil', type: 'single_choice', options: ['hijab', 'niqab', 'none'] },
        { key: 'femaleProfile.acceptPolygamy', type: 'single_choice', options: ['yes', 'no', 'conditional'] },
        { key: 'femaleProfile.wantsToWork', type: 'single_choice', options: ['yes', 'no', 'flexible'] },
      ],
    },
    {
      id: 'male_profile',
      title: 'Profil specifique frere',
      appliesTo: ['male'],
      fields: [
        { key: 'physicalCharacteristics.height', type: 'number_cm' },
        { key: 'physicalCharacteristics.bodyType', type: 'single_choice', options: ['slim', 'average', 'strong'] },
        { key: 'maleProfile.professionalSituation', type: 'single_choice', options: ['student', 'employee', 'entrepreneur', 'other'] },
        { key: 'maleProfile.financialStability', type: 'single_choice', options: ['stable', 'building'] },
        { key: 'maleProfile.polygamyStatus', type: 'single_choice', options: ['no', 'possible', 'already_married'] },
      ],
    },
    {
      id: 'male_search',
      title: 'Ce que le frere recherche',
      appliesTo: ['male'],
      fields: [
        { key: 'searchCriteria.ageMin', type: 'number' },
        { key: 'searchCriteria.ageMax', type: 'number' },
        { key: 'searchCriteria.acceptedMaritalStatuses', type: 'multi_choice', options: ['single', 'divorced', 'widowed', 'any'] },
        { key: 'searchCriteria.acceptWithChildren', type: 'single_choice', options: ['yes', 'no', 'limited', 'any'] },
        { key: 'searchCriteria.preferredNationalities', type: 'multi_text' },
        { key: 'searchCriteria.preferredOrigins', type: 'multi_text' },
        { key: 'searchCriteria.preferredEthnicities', type: 'multi_choice', options: [...ETHNICITIES, 'any'] },
        { key: 'searchCriteria.desiredResidence', type: 'single_choice', options: ['same_country', 'europe_only', 'worldwide', 'any'] },
        { key: 'searchCriteria.desiredReligiousPractice', type: 'single_choice', options: ['little', 'practicing', 'very_practicing', 'any'] },
        { key: 'searchCriteria.prayersExpectation', type: 'single_choice', options: ['regular_required', 'progress_accepted', 'any'] },
        { key: 'searchCriteria.madhhabPreferenceType', type: 'single_choice', options: ['same', 'any', 'specific'] },
        { key: 'searchCriteria.madhhabSpecific', type: 'text_if_specific' },
        { key: 'searchCriteria.desiredReligiousFollowing', type: 'single_choice', options: ['student', 'self_taught', 'any'] },
        { key: 'searchCriteria.hijraVision', type: 'single_choice', options: ['must_hijra', 'open_hijra', 'not_desired', 'any'] },
        { key: 'searchCriteria.heightMin', type: 'number_cm' },
        { key: 'searchCriteria.heightMax', type: 'number_cm' },
        { key: 'searchCriteria.preferredBodyType', type: 'single_choice', options: ['slim', 'average', 'strong', 'any'] },
        { key: 'searchCriteria.femaleHijabPreference', type: 'single_choice', options: ['required', 'niqab_only', 'hijab_ok', 'any'] },
        { key: 'searchCriteria.desiredWorkPreference', type: 'single_choice', options: ['yes', 'no', 'flexible', 'any'] },
        { key: 'searchCriteria.polygamyPreference', type: 'single_choice', options: ['yes', 'future_possible', 'monogamy_only', 'any'] },
        { key: 'searchCriteria.wantsChildrenPreference', type: 'single_choice', options: ['yes', 'no', 'undecided', 'any'] },
        { key: 'searchCriteria.desiredChildrenCount', type: 'number' },
        { key: 'searchCriteria.relocationRequirement', type: 'single_choice', options: ['required', 'flexible', 'not_required', 'any'] },
      ],
    },
    {
      id: 'female_search',
      title: 'Ce que la soeur recherche',
      appliesTo: ['female'],
      fields: [
        { key: 'searchCriteria.ageMin', type: 'number' },
        { key: 'searchCriteria.ageMax', type: 'number' },
        { key: 'searchCriteria.acceptedMaritalStatuses', type: 'multi_choice', options: ['single', 'divorced', 'widowed', 'any'] },
        { key: 'searchCriteria.acceptAlreadyMarried', type: 'single_choice', options: ['yes', 'no', 'any'] },
        { key: 'searchCriteria.acceptWithChildren', type: 'single_choice', options: ['yes', 'no', 'conditional', 'any'] },
        { key: 'searchCriteria.preferredNationalities', type: 'multi_text' },
        { key: 'searchCriteria.preferredOrigins', type: 'multi_text' },
        { key: 'searchCriteria.preferredEthnicities', type: 'multi_choice', options: [...ETHNICITIES, 'any'] },
        { key: 'searchCriteria.desiredResidence', type: 'single_choice', options: ['same_country', 'europe_only', 'worldwide', 'any'] },
        { key: 'searchCriteria.desiredReligiousPractice', type: 'single_choice', options: ['little', 'practicing', 'very_practicing', 'any'] },
        { key: 'searchCriteria.prayersExpectation', type: 'single_choice', options: ['regular_required', 'progress_accepted', 'any'] },
        { key: 'searchCriteria.madhhabPreferenceType', type: 'single_choice', options: ['same', 'any', 'specific'] },
        { key: 'searchCriteria.madhhabSpecific', type: 'text_if_specific' },
        { key: 'searchCriteria.desiredReligiousFollowing', type: 'single_choice', options: ['student', 'serious_self_taught', 'any'] },
        { key: 'searchCriteria.hijraVision', type: 'single_choice', options: ['must_hijra', 'open_hijra', 'not_desired', 'any'] },
        { key: 'searchCriteria.heightMin', type: 'number_cm' },
        { key: 'searchCriteria.heightMax', type: 'number_cm' },
        { key: 'searchCriteria.preferredBodyType', type: 'single_choice', options: ['slim', 'average', 'strong', 'any'] },
        { key: 'searchCriteria.maleBeardPreference', type: 'single_choice', options: ['required', 'preferred', 'any'] },
        { key: 'searchCriteria.maleProfessionalMinimum', type: 'single_choice', options: ['student_ok', 'employee_min', 'entrepreneur', 'any'] },
        { key: 'searchCriteria.maleFinancialStabilityRequirement', type: 'single_choice', options: ['required', 'building_ok', 'any'] },
        { key: 'searchCriteria.maleAmbition', type: 'single_choice', options: ['very_ambitious', 'stable', 'any'] },
        { key: 'searchCriteria.polygamyPreference', type: 'single_choice', options: ['yes', 'no', 'conditional', 'any'] },
        { key: 'searchCriteria.wantsChildrenPreference', type: 'single_choice', options: ['yes', 'no', 'undecided', 'any'] },
        { key: 'searchCriteria.desiredChildrenCount', type: 'number' },
        { key: 'searchCriteria.relocationRequirement', type: 'single_choice', options: ['yes', 'no', 'flexible', 'any'] },
      ],
    },
  ],
};

const AI_QUESTIONS = {
  male: {
    vision: [
      'As-tu deja ete marie ou fiance ? Qu est-ce que tu en retiens ?',
      'Pourquoi souhaites-tu te marier maintenant ?',
      'Quelle est ta conception du mariage en Islam ?',
      'Penses-tu que le mariage est pour la vie, quoi qu il arrive ?',
      'Qu attends-tu concretement de ta future femme au quotidien ?',
      'Pour toi, quel est le role de l homme dans le foyer ?',
      'Pour toi, quel est le role de la femme dans le foyer ?',
      'Comment imagines-tu la vie de couple au quotidien ?',
      'Quelles sont les valeurs les plus importantes dans un couple selon toi ?',
      'Qu est-ce qui peut, selon toi, detruire un mariage ?',
      'Qu est-ce qui fait durer un mariage selon toi ?',
    ],
    communication: [
      'Comment reagis-tu quand tu es en colere ?',
      'As-tu tendance a parler facilement de tes problemes ?',
      'Comment preferes-tu regler les conflits dans un couple ?',
      'Es-tu quelqu un de rancunier ? Pardonnes-tu facilement ?',
      'As-tu besoin de temps seul apres une dispute avant de reprendre la discussion ?',
      'Comment reagis-tu quand on te fait une critique ?',
      'Preferes-tu regler les problemes rapidement ou prendre du recul d abord ?',
      'Comment aimerais-tu que ta femme reagisse en cas de conflit ?',
    ],
    family: [
      'Comment decris-tu ta relation avec ta famille ?',
      'Es-tu tres proche de ta famille ? A quelle frequence les vois-tu ?',
      'Quelle relation aimerais-tu que ta femme ait avec ta famille ?',
      'Comment reagirais-tu s il y a un conflit entre ta femme et ta famille ?',
      'Penses-tu qu il faut poser des limites avec la belle-famille ?',
      'Quelle place doit avoir la belle-famille dans la vie du couple ?',
      'Que penses-tu de l amitie homme-femme ?',
    ],
    finance_and_projects: [
      'Comment geres-tu ton argent au quotidien ?',
      'Es-tu plutot depensier ou econome ?',
      'As-tu des credits ou des dettes en cours ?',
      'Es-tu financierement responsable d autres personnes ?',
      'Comment vois-tu le partage des depenses dans le couple ? Compte commun ou separe ?',
      'Ou aimerais-tu vivre dans le futur ?',
      'Comment imagines-tu ta vie dans 5 ans ? Et dans 10 ans ?',
      'Quels sont tes objectifs et tes reves pour l avenir ?',
    ],
    parenting: [
      'Comment vois-tu l education de tes enfants ?',
      'Penses-tu qu il faut etre strict ou plutot souple avec les enfants ?',
      'Comment imagines-tu ton role de pere au quotidien ?',
      'Quelle relation aimerais-tu avoir avec tes enfants ?',
      'Quelles valeurs aimerais-tu leur transmettre ?',
      'Que ferais-tu en cas d impossibilite medicale d avoir des enfants ?',
      'Que penses-tu de l ecole publique vs ecole islamique ?',
    ],
    religion: [
      'Comment decris-tu ton rapport personnel a Allah et a ta deen ?',
      'Aimes-tu apprendre et approfondir ta religion ?',
      'Que penses-tu de l apprentissage religieux en couple ?',
      'Comment vois-tu l evolution spirituelle du couple dans le temps ?',
      'Qu attends-tu de ta femme sur le plan religieux au quotidien ?',
    ],
    personality: [
      'Selon toi, quelles sont tes plus grandes qualites ?',
      'Quels sont tes principaux defauts que tu reconnais ?',
      'Te consideres-tu plutot introverti ou extraverti ?',
      'Es-tu quelqu un de patient face aux difficultes ?',
      'Te consideres-tu affectueux ou plutot reserve ?',
      'Es-tu plutot optimiste ou pessimiste ?',
      'Comment geres-tu la pression et le stress ?',
      'As-tu un temperament jaloux ou possessif ?',
      'As-tu besoin de beaucoup d attention et de reconnaissance ?',
    ],
    lifestyle: [
      'Comment passes-tu ton temps libre ?',
      'Quels sont tes loisirs et passions ?',
      'Fais-tu du sport ? Si oui, a quelle frequence ?',
      'Aimes-tu voyager ? Quel type de voyage preferes-tu ?',
      'Quelle importance donnes-tu a la sante et a l alimentation ?',
      'Es-tu casanier ou tu aimes sortir souvent ?',
      'Comment imagines-tu les week-ends en couple ?',
      'Aimes-tu recevoir des invites a la maison ?',
      'Es-tu plutot maniaque ou desordonne dans ton quotidien ?',
      'Quelle importance donnes-tu au temps de qualite passe ensemble ?',
    ],
    intimacy: [
      'Comment montres-tu ton amour et ton affection ?',
      'Quelle importance donnes-tu a la complicite dans le mariage ?',
      'Comment envisages-tu d entretenir la flamme sur le long terme ?',
      'As-tu besoin de beaucoup d affection et de tendresse au quotidien ?',
      'Comment geres-tu les periodes difficiles dans une relation ?',
      'Comment renforces-tu la confiance dans un mariage selon toi ?',
    ],
  },
  female: {
    vision: [
      'Pourquoi souhaites-tu te marier maintenant ?',
      'Quelle est ta conception du mariage en Islam ?',
      'Penses-tu que le mariage est pour la vie, quoi qu il arrive ?',
      'Qu attends-tu concretement de ton futur mari au quotidien ?',
      'Comment imagines-tu la vie de couple au quotidien ?',
      'Quelles sont les valeurs les plus importantes dans un couple selon toi ?',
      'Qu est-ce qui peut, selon toi, detruire un mariage ?',
      'Qu est-ce qui fait durer un mariage selon toi ?',
    ],
    communication: [
      'Comment reagis-tu quand tu es en colere ou blessee ?',
      'As-tu tendance a parler facilement de tes problemes ?',
      'Comment preferes-tu regler les conflits dans un couple ?',
      'Es-tu quelqu un de rancuniere ? Pardonnes-tu facilement ?',
      'As-tu besoin de temps seule apres une dispute avant de reprendre la discussion ?',
      'Comment reagis-tu quand on te fait une critique ?',
      'Comment aimerais-tu que ton mari gere les conflits ?',
    ],
    family: [
      'Comment decris-tu ta relation avec ta famille ?',
      'Es-tu tres proche de ta famille ? A quelle frequence les vois-tu ?',
      'Quelle place donnes-tu a la belle-famille dans ta vie de couple ?',
      'Comment reagirais-tu face a un conflit avec la belle-famille ?',
      'Que penses-tu de l amitie homme-femme ?',
    ],
    finance_and_projects: [
      'Comment geres-tu ton argent au quotidien ?',
      'As-tu des credits ou des dettes en cours ?',
      'Ou aimerais-tu vivre dans le futur ?',
      'Comment imagines-tu ta vie dans 5 ans ? Et dans 10 ans ?',
      'Quels sont tes objectifs et tes reves pour l avenir ?',
      'Qu est-ce qui te rendrait fiere dans ta vie ?',
    ],
    parenting: [
      'Comment vois-tu l education de tes enfants ?',
      'Penses-tu qu il faut etre stricte ou plutot souple avec les enfants ?',
      'Comment imagines-tu ton role de mere au quotidien ?',
      'Quelle relation aimerais-tu avoir avec tes enfants ?',
      'Quelles valeurs aimerais-tu leur transmettre ?',
      'Que ferais-tu en cas d impossibilite medicale d avoir des enfants ?',
      'Que penses-tu de l ecole publique vs ecole islamique ?',
    ],
    religion: [
      'Comment decris-tu ton rapport personnel a Allah et a ta deen ?',
      'Aimes-tu apprendre et approfondir ta religion ?',
      'Que penses-tu de l apprentissage religieux en couple ?',
      'Comment vois-tu l evolution spirituelle du couple dans le temps ?',
      'Qu attends-tu de ton mari sur le plan religieux au quotidien ?',
    ],
    personality: [
      'Selon toi, quelles sont tes plus grandes qualites ?',
      'Quels sont tes principaux defauts que tu reconnais ?',
      'Te consideres-tu plutot introvertie ou extravertie ?',
      'Es-tu quelqu un de patiente face aux difficultes ?',
      'Te consideres-tu affectueuse ou plutot reservee ?',
      'Es-tu plutot optimiste ou pessimiste ?',
      'Comment geres-tu la pression et le stress ?',
      'As-tu un temperament jaloux ou possessif ?',
      'As-tu besoin de beaucoup d attention et de reconnaissance ?',
    ],
    lifestyle: [
      'Comment passes-tu ton temps libre ?',
      'Quels sont tes loisirs et passions ?',
      'Fais-tu du sport ? Si oui, a quelle frequence ?',
      'Aimes-tu voyager ? Quel type de voyage preferes-tu ?',
      'Quelle importance donnes-tu a la sante et a l alimentation ?',
      'Es-tu casaniere ou tu aimes sortir souvent ?',
      'Comment imagines-tu les week-ends en couple ?',
      'Aimes-tu recevoir des invites a la maison ?',
      'Es-tu plutot maniaque ou desordonnee dans ton quotidien ?',
      'Quelle importance donnes-tu au temps de qualite passe ensemble ?',
    ],
    intimacy: [
      'Comment montres-tu ton amour et ton affection ?',
      'Quelle importance donnes-tu a la complicite dans le mariage ?',
      'Comment envisages-tu d entretenir la flamme sur le long terme ?',
      'As-tu besoin de beaucoup d affection et de tendresse au quotidien ?',
      'Comment geres-tu les periodes difficiles dans une relation ?',
    ],
  },
};

module.exports = {
  REGISTRATION_QUESTIONNAIRE,
  AI_QUESTIONS,
};
